### ISSUE TITLE
download test project to google drive

### ISSUE THREAD

**Issue by kevinReynaud** [grahamoverby/Godot-Open-Dialogue-Expansion#1]
Could you upload the test project in a zip file, since google drive doesn't let you download the compmeta folder, thanks for the help

**Comment by thetainfelix** [comment]
Yes!! I added the sample project as a zip to the linked google drive folder. good catch, i didn't know about the compmeta thing. lemme know how it works for you

**Comment by kevinReynaud** [comment]
Thanks it worked.
